services:
  accounts:
    image: "avnish09/accounts:01"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - modern-microservices
  loans:
    image: "avnish09/loans:01"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - modern-microservices
  cards:
    image: "avnish09/cards:01"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - modern-microservices
networks:
  modern-microservices:
    driver: "bridge"